---
variables:
  PYVERSION: "latest"

python:build:
  image: registry.gitlab.com/notno/ci/images/python:$PYVERSION
  stage: build
  script:
    - pip3 install build
    - python -m build
  artifacts:
    paths:
      - dist
  needs: []
