---
variables:
  PYTHON_PACKAGE: "templates_tests/python/mypackage"

include:
  - local: "alm/semantic-release.yml"

  - local: "other/badge.yml"

  - local: "docker/kaniko.yml"
  - local: "docker/anchore/grype.yml"

  - local: "python/bandit.yml"
  - local: "python/black.yml"
  - local: "python/pip-outdated.yml"
  - local: "python/pytest.yml"
  - local: "python/mypy.yml"
  - local: "python/pylint.yml"
  - local: "python/safety.yml"
  - local: "python/wily.yml"

  - local: "c/cppcheck.yml"
  - local: "c/flawfinder.yml"

  - local: "yaml/yamllint.yml"

docker:kaniko:
  variables:
    CONTEXT: templates_tests/python

yaml:yamllint:
  allow_failure: true # for now

# We only check if it runs properly, not if our image has problems
docker:anchore:grype:
  variables:
    GRYPE_FAIL_ON: ""

python:pytest:
  before_script:
    # We need to move here so it's added to PYTHONPATH
    - cd templates_tests/python
  variables:
    # Not happy with this, but we need it so --cov works
    # without breaking other jobs
    PYTHON_PACKAGE: mypackage

c:cppcheck:
  variables:
    ERROR_EXIT_CODE: 0
    CHECK_PATH: templates_tests/c

c:flawfinder:
  variables:
    ERROR_LEVEL: "6"
    CHECK_PATH: templates_tests/c

workflow:
  rules:
    # Run if we're in a merge request
    - if: $CI_MERGE_REQUEST_IID
    # Run for tags, so we get semantic versioning
    - if: $CI_COMMIT_TAG
    # Run for changes on the master branch (so merged MRs)
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Run for manually triggered jobs from gitlab UI
    - if: $CI_PIPELINE_SOURCE == 'web'

# We keep this downstream, as we don't expect many MRs for this specific test
downstream:pages:
  stage: test
  trigger:
    project: ci/tests/pages
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - changes:
        - other/pages-hugo.yml

# We keep this downstream, as we don't expect many MRs for this specific test
downstream:pandoc:
  stage: test
  trigger:
    project: template/report
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - changes:
        - docs/report-pandoc.yml

semantic-release:dry-run:
  extends: semantic-release
  variables:
    EXTRA_ARGS: "--dry-run --branches testing"
  rules:
    - if: '$CI_COMMIT_BRANCH == "testing"'
