---
# CI of ci/templates itself

variables:
  SCHEDULE_PIPELINE_PROJECT_IDS:
    30771297 30771293 30771284 30771254 30771239 30933363
  SCHEDULE_PIPELINE_DESCRIPTION: CI Daily Update
  SCHEDULE_PIPELINE_CRON: 0 10 * * * # Every day at 10:00
  GITLAB_RECOMMENDED_AUTO_FIX: "true"
  RELEASE_CHANGELOG: "false"

include:
  - local: pipelines/project-automation.yml
  - local: yaml/yamllint.yml
  - local: project-automation/pipeline-scheduler.yml
  - local: project-automation/pages-hugo.yml
  - local: project-automation/gitlab/py-in-ci.yml
  - local: docs/prettier.yml

pages:
  stage: test
  variables:
    HUGO_BASEURL: ${CI_PAGES_URL}
  before_script:
    - cd tests/mockup_projects/pages
    - git clone https://github.com/alexandrevicenzi/soho.git themes/soho
    - mkdir content
    - cp ${CI_PROJECT_DIR}/README.md content/index.md
  needs: []

# child pipeline to unit tests all our jobs

jobs:c:
  stage: test
  trigger:
    include:
      - local: tests/jobs/c.yml
    strategy: depend

jobs:kaniko:
  stage: test
  trigger:
    include:
      - local: tests/jobs/kaniko.yml
    strategy: depend

jobs:buildah:
  stage: test
  trigger:
    include:
      - local: tests/jobs/buildah.yml
    strategy: depend

jobs:docs:
  stage: test
  trigger:
    include:
      - local: tests/jobs/docs.yml
    strategy: depend

jobs:python:
  stage: test
  trigger:
    include:
      - local: tests/jobs/python.yml
    strategy: depend

jobs:python:custom-image:
  stage: test
  trigger:
    include:
      - local: tests/jobs/python-custom-image.yml
    strategy: depend

# child pipelines to test our off-the-shelf pipelines
pipelines:c:
  stage: test
  trigger:
    include:
      - local: tests/pipelines/c.yml
    strategy: depend

pipelines:python:
  stage: test
  trigger:
    include:
      - local: tests/pipelines/python.yml
    strategy: depend

pipelines:container:polyrepo:
  stage: test
  trigger:
    include:
      - local: tests/pipelines/container/polyrepo.yml
    strategy: depend

pipelines:kaniko:monorepo:
  stage: test
  trigger:
    include:
      - local: tests/pipelines/container/monorepo.yml
    strategy: depend

pipelines:kaniko:python:
  stage: test
  trigger:
    include:
      - local: tests/pipelines/container/python.yml
    strategy: depend
