---
include:
  - remote: https://jobs.just-ci.dev/56-fix-python-pytest-do-not-add-cwd-to-path/python/generic.yml

python:build:
  extends: .python:pre
  stage: build
  variables:
    JOB_PACKAGE: build
  script:
    - !reference [".python:pre", script]
    - python -m build . --outdir ${CI_PROJECT_DIR}/dist
  artifacts:
    paths:
      - dist
  needs: []
