---
include:
  - remote: "https://jobs.just-ci.dev/v4.0.0-beta.6/project-automation/find-next-release.yml"
  - remote: "https://jobs.just-ci.dev/v4.0.0-beta.6/project-automation/gitlab-recommended.yml"
  - remote: "https://jobs.just-ci.dev/v4.0.0-beta.6/project-automation/semantic-release.yml"
  - remote: "https://jobs.just-ci.dev/v4.0.0-beta.6/project-automation/badge.yml"
  - remote: "https://jobs.just-ci.dev/v4.0.0-beta.6/project-automation/check-GL-token.yml"
  - remote: "https://jobs.just-ci.dev/v4.0.0-beta.6/python/tbump.yml"

tbump:
  rules:
    - exists:
        - 'tbump.toml'

badge:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'parent_pipeline'
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
