---
# CI of ci/templates itself

stages:
  - test
  - pre-release

include:
  - local: pipelines/project-automation.yml
  - local: pipelines/workflow.yml
  - local: yaml/yamllint.yml

gitlab:recommended:
  variables:
    GITLAB_RECOMMENDED_AUTO_FIX: "true"

tbump:
  stage: pre-release

# child pipeline to unit tests all our jobs

jobs:c:
  stage: test
  trigger:
    include:
      - local: tests/jobs/c.yml
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS

jobs:docker:
  stage: test
  trigger:
    include:
      - local: tests/jobs/docker.yml
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS

jobs:docs:
  stage: test
  trigger:
    include:
      - local: tests/jobs/docs.yml
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS

jobs:python:
  stage: test
  trigger:
    include:
      - local: tests/jobs/python.yml
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS

# downstream multi project pipelines that test one job

downstream:pages:
  stage: test
  trigger:
    project: ci/tests/pages
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS

downstream:pandoc:
  stage: test
  trigger:
    project: template/report
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS

# child pipelines to test our off-the-shelves pipelines
pipelines:c:
  stage: test
  trigger:
    include:
      - local: tests/pipelines/c.yml
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS

pipelines:docker:
  stage: test
  trigger:
    include:
      - local: tests/pipelines/docker.yml
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS

pipelines:python:
  stage: test
  trigger:
    include:
      - local: tests/pipelines/python.yml
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS

pipelines:python&docker:
  stage: test
  trigger:
    include:
      - local: tests/pipelines/python-docker.yml
    strategy: depend
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS
