---
include:
  - remote: https://jobs.just-ci.dev/v6.1.0-beta.2/project-automation/workflow.yml
  - remote: https://jobs.just-ci.dev/v6.1.0-beta.2/project-automation/find-next-release.yml
  - remote: https://jobs.just-ci.dev/v6.1.0-beta.2/project-automation/gitlab-recommended.yml
  - remote: https://jobs.just-ci.dev/v6.1.0-beta.2/project-automation/semantic-release.yml
  - remote: https://jobs.just-ci.dev/v6.1.0-beta.2/project-automation/generic.yaml
  - remote: https://jobs.just-ci.dev/v6.1.0-beta.2/python/tbump.yml

tbump:
  extends: .release:rules
  needs: [find-next-release]
